### ISSUE TITLE
Switch from BzAPI to the Bugzilla native REST API

### ISSUE THREAD

**Issue by edmorley** [mnoorenberghe/bz-dependency-buglist#1]
Since the former is deprecated and 2-10x slower in many cases. See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1301541
https://bugzilla.mozilla.org/show_bug.cgi?id=1035804

https://github.com/mnoorenberghe/bz-dependency-buglist/blob/cd53d5d8f76f5e2aebf5c0f1bc2d601be4caad06/tracker.js#L328

**Comment by mnoorenberghe** [comment]
Hmm… I honestly thought I switched years ago… one of the reasons was because it was so slow…

**Comment by mnoorenberghe** [comment]
Oh, now I understand… in 7bad9b6646f5637dcf44f35feded06b353b78181 I switched from the bzAPI server (extremely slow as it did a remote connection itself) to using the bzAPI compatibility layer on BMO which was much faster.
